CREATE TABLE IF NOT EXISTS properties (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  slug VARCHAR(191) NOT NULL,
  title VARCHAR(150) NOT NULL,
  category VARCHAR(50) NOT NULL,
  location VARCHAR(150) NOT NULL,
  address VARCHAR(255) NOT NULL,
  price BIGINT UNSIGNED NOT NULL,
  thumbnail_url VARCHAR(255) NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  promo_badge VARCHAR(100) NULL,
  short_description VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  bedrooms TINYINT UNSIGNED NULL,
  bathrooms TINYINT UNSIGNED NULL,
  building_area INT UNSIGNED NULL,
  land_area INT UNSIGNED NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'available',
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY properties_slug_unique (slug),
  KEY properties_status_index (status),
  KEY properties_is_featured_index (is_featured)
);

INSERT INTO properties (
  slug,
  title,
  category,
  location,
  address,
  price,
  thumbnail_url,
  image_url,
  promo_badge,
  short_description,
  description,
  bedrooms,
  bathrooms,
  building_area,
  land_area,
  status,
  is_featured
)
SELECT * FROM (
  SELECT
    'royal-merit-lodge' AS slug,
    'Royal Merit Lodge' AS title,
    'villa' AS category,
    'Bali, Indonesia' AS location,
    'Jl. Mellow Creek No. 18, Ubud, Bali, Indonesia' AS address,
    750000000 AS price,
    '/uploads/properties/splash.jpg' AS thumbnail_url,
    '/uploads/properties/splash.jpg' AS image_url,
    'Staycation Deal' AS promo_badge,
    'A private retreat with warm modern interiors and a calm neighborhood atmosphere.' AS short_description,
    'A private retreat with a warm modern bedroom concept, premium wooden finishes, and fast access to Ubud culinary destinations. Suitable for short family stays, remote workers, and guests who want a quiet but strategic location.' AS description,
    2 AS bedrooms,
    2 AS bathrooms,
    96 AS building_area,
    120 AS land_area,
    'available' AS status,
    TRUE AS is_featured
  UNION ALL
  SELECT
    'cluster-sunrise-residence',
    'Cluster Sunrise Residence',
    'rumah',
    'Bandung Timur',
    'Jl. Cisaranten Kulon No. 12, Bandung Timur',
    650000000,
    '/uploads/properties/splash.jpg',
    '/uploads/properties/splash.jpg',
    'Diskon Booking Fee 25%',
    'Hunian keluarga dengan akses cepat ke sekolah, pasar, dan jalan utama.',
    'Cluster Sunrise Residence menghadirkan rumah modern untuk keluarga muda dengan tata ruang lega, keamanan 24 jam, dan akses cepat ke area pendidikan serta pusat belanja Bandung Timur.',
    3,
    2,
    90,
    108,
    'available',
    TRUE
  UNION ALL
  SELECT
    'villa-green-valley',
    'Villa Green Valley',
    'villa',
    'Lembang',
    'Jl. Maribaya Resort No. 7, Lembang, Bandung Barat',
    1200000000,
    '/uploads/properties/splash.jpg',
    '/uploads/properties/splash.jpg',
    'Gratis Biaya KPR 1 Tahun',
    'Villa premium dengan pemandangan bukit dan udara sejuk sepanjang hari.',
    'Villa Green Valley cocok untuk keluarga yang mengutamakan kenyamanan tinggal dan pertumbuhan nilai aset jangka panjang. Memiliki panorama hijau, area semi outdoor, dan suasana resort yang tenang.',
    4,
    3,
    180,
    240,
    'available',
    TRUE
  UNION ALL
  SELECT
    'ruko-prime-bisnis',
    'Ruko Prime Bisnis',
    'ruko',
    'Kota Bandung',
    'Jl. Soekarno Hatta No. 88, Kota Bandung',
    980000000,
    '/uploads/properties/splash.jpg',
    '/uploads/properties/splash.jpg',
    'Cashback Furnitur 15 Juta',
    'Ruko strategis di jalan utama dengan parkir depan yang lega.',
    'Ruko Prime Bisnis dirancang untuk usaha retail maupun kantor cabang dengan visibilitas tinggi dari jalan utama, akses logistik mudah, dan area komersial yang terus berkembang.',
    1,
    1,
    120,
    72,
    'available',
    FALSE
  UNION ALL
  SELECT
    'kost-urban-living',
    'Kost Urban Living',
    'kos',
    'Cimahi',
    'Jl. Amir Machmud No. 144, Cimahi',
    1850000000,
    '/uploads/properties/splash.jpg',
    '/uploads/properties/splash.jpg',
    'Investasi Kos Produktif',
    'Kos modern dengan potensi investasi yang stabil di area kampus.',
    'Kost Urban Living menawarkan bangunan kos siap beli dengan akses internet cepat, sistem keamanan area, dan jarak dekat ke kampus serta pusat kuliner Cimahi. Cocok untuk investor yang mencari aset produktif dan bernilai jual kembali.',
    1,
    1,
    24,
    24,
    'available',
    FALSE
) AS seed_rows
WHERE NOT EXISTS (
  SELECT 1 FROM properties WHERE properties.slug = seed_rows.slug
);
