ALTER TABLE properties
ADD COLUMN cluster_name VARCHAR(150) NULL AFTER location,
ADD COLUMN google_maps_link VARCHAR(255) NULL AFTER address,
ADD COLUMN ruang_tamu TINYINT UNSIGNED NULL AFTER bathrooms,
ADD COLUMN dapur TINYINT UNSIGNED NULL AFTER ruang_tamu,
ADD COLUMN garasi TINYINT UNSIGNED NULL AFTER dapur,
ADD COLUMN carport TINYINT UNSIGNED NULL AFTER garasi,
ADD COLUMN sertifikat VARCHAR(100) NULL AFTER carport,
ADD COLUMN daya_listrik INT UNSIGNED NULL AFTER sertifikat,
ADD COLUMN tahun_dibangun YEAR NULL AFTER daya_listrik,
ADD COLUMN hadap_rumah VARCHAR(50) NULL AFTER tahun_dibangun,
ADD COLUMN sumber_air VARCHAR(100) NULL AFTER hadap_rumah,
ADD COLUMN fasilitas_tambahan TEXT NULL AFTER sumber_air,
ADD COLUMN is_draft BOOLEAN NOT NULL DEFAULT FALSE AFTER is_featured;

CREATE TABLE IF NOT EXISTS property_images (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  property_id BIGINT UNSIGNED NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  display_order SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY property_images_property_id_index (property_id),
  CONSTRAINT property_images_property_id_foreign
    FOREIGN KEY (property_id) REFERENCES properties (id) ON DELETE CASCADE
);
